name: Build PLD
on:
  push:
    tags:
      - '*'

jobs:
  build-pld:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Build PLD
        uses: ./.github/actions/pld-builder

      - name: publish PLD
        uses: ncipollo/release-action@v1
        if: ${{ github.ref }}
        with:
          artifacts: "pld.pdf"
          token: ${{ secrets.ACCESS_TOKEN }}
