name: Build PLD
on:
  push:
    tags:
      - '*'
    branches:
      - 'master'
      - 'improve_workflow'

jobs:
  build-pld:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Build PLD
        uses: ./.github/actions/pld-builder

      - name: Rename PLD
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: mv pld.pdf 2023_PLD_Pizzi_$(date +"%Y%m").pdf

      - name: publish PLD
        uses: ncipollo/release-action@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          artifacts: "2023_PLD_Pizzi*.pdf"
          token: ${{ secrets.ACCESS_TOKEN }}
