name: Build PLD
on:
  push:
    tags:
      - '*'
    branches:
      - 'master'
      - 'improve-workflow'

jobs:
  build-pld:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Login to github registery.
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u PizziPayment --password-stdin

      - name: ls
        run: ls && pwd

      - name: Build PLD
        run: docker run ghcr.io/pizzipayment/pld_builder:latest -v "/home/runner/work/PizziPLD/PizziPLD:/source"

      - name: Rename PLD
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: mv pld.pdf 2023_PLD_Pizzi_$(date +"%Y%m").pdf

      - name: publish PLD
        uses: ncipollo/release-action@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          artifacts: "2023_PLD_Pizzi*.pdf"
          token: ${{ secrets.GITHUB_TOKEN }}
