name: Build PLD builder image
on:
  push:
    paths:
      - .github/actions/**

jobs:
  build-pld:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Login to github registery.
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u PizziPayment --password-stdin

      - name: Build the docker image.
        run: docker build . --tag ghcr.io/pizzipayment/pld_builder:latest

      - name: Publish the image to the registery
        run: docker push ghcr.io/PizziPayment/PLDBuilder:latest
